#!/bin/bash
# Deployment Commands for Malaika Nest
# Run these commands on your server (SSH into your GCP VM)

echo "=== MALAIKA NEST DEPLOYMENT COMMANDS ==="
echo ""
echo "1. SSH into your server:"
echo "   ssh root@104.154.161.10"
echo ""
echo "2. Clone the project (first time only):"
echo "   cd /opt"
echo "   git clone https://github.com/error302/malaikanest.git"
echo "   cd malaikanest"
echo ""
echo "3. Setup environment file:"
echo "   cp .env.example backend/.env"
echo "   nano backend/.env"
echo ""
echo "4. Install backend dependencies and run migrations:"
echo "   cd backend"
echo "   pip install -r requirements.txt"
echo "   python manage.py migrate"
echo "   python manage.py collectstatic --noinput"
echo ""
echo "5. Install frontend and build:"
echo "   cd ../frontend"
echo "   npm install"
echo "   npm run build"
echo ""
echo "6. Get SSL Certificate (run after DNS propagates):"
echo "   sudo certbot --nginx -d malaikanest.duckdns.org"
echo ""
echo "7. Restart services:"
echo "   pm2 restart all"
echo ""
echo "=== Your site will be live at: https://malaikanest.duckdns.org ==="

