#!/bin/bash
# Deployment Commands for Malaika Nest
# Run these commands on your server (SSH into your GCP VM)

echo "=== MALAIKA NEST DEPLOYMENT COMMANDS ==="
echo ""
echo "1. SSH into your server:"
echo "   ssh root@104.154.161.10"
echo ""
echo "2. Navigate to project directory:"
echo "   cd /opt/malaikanest"
echo ""
echo "3. Pull latest code:"
echo "   git pull origin main"
echo ""
echo "4. Get SSL Certificate (run after DNS propagates):"
echo "   sudo certbot --nginx -d malaikanest.duckdns.org"
echo ""
echo "5. Setup environment file:"
echo "   cp .env.example backend/.env"
echo "   nano backend/.env"
echo ""
echo "6. Install & build:"
echo "   cd backend && pip install -r requirements.txt"
echo "   python manage.py migrate"
echo "   cd ../frontend && npm install && npm run build"
echo ""
echo "7. Restart services (if using PM2):"
echo "   pm2 restart all"
echo ""
echo "8. Or use Docker Compose:"
echo "   docker-compose -f docker-compose.prod.yml up -d --build"
echo ""
echo "=== Your site will be live at: https://malaikanest.duckdns.org ==="

