# Generated by Codex on 2026-03-17

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("site_name", models.CharField(default="Malaika Nest", max_length=120)),
                ("site_description", models.CharField(blank=True, default="Premium Baby Products in Kenya", max_length=255)),
                ("contact_email", models.EmailField(default="malaikanest7@gmail.com", max_length=254)),
                ("contact_phone", models.CharField(blank=True, default="+254700000000", max_length=40)),
                ("address", models.CharField(blank=True, default="Nairobi, Kenya", max_length=180)),
                ("facebook_url", models.URLField(blank=True, default="")),
                ("instagram_url", models.URLField(blank=True, default="")),
                ("twitter_url", models.URLField(blank=True, default="")),
                ("shipping_fee", models.DecimalField(decimal_places=2, default=500, max_digits=10)),
                ("free_shipping_threshold", models.DecimalField(decimal_places=2, default=5000, max_digits=10)),
                ("minimum_order_amount", models.DecimalField(decimal_places=2, default=1000, max_digits=10)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="site/logo/")),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Site Settings",
                "verbose_name_plural": "Site Settings",
            },
        ),
    ]

