# Generated by Django 5.1.15 on 2026-07-30 22:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_shopphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_email',
            field=models.EmailField(default='hello@malaikanest.com', max_length=254),
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email_type', models.CharField(db_index=True, max_length=40)),
                ('recipient', models.EmailField(db_index=True, max_length=254)),
                ('subject', models.CharField(blank=True, default='', max_length=255)),
                ('template_name', models.CharField(blank=True, default='', max_length=120)),
                ('success', models.BooleanField(db_index=True, default=False)),
                ('duration_ms', models.PositiveIntegerField(default=0, help_text='SMTP round-trip in milliseconds')),
                ('error_message', models.TextField(blank=True, default='')),
                ('order_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
            ],
            options={
                'verbose_name': 'Email Log',
                'verbose_name_plural': 'Email Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='core_emaill_created_7c6fcb_idx'), models.Index(fields=['email_type', '-created_at'], name='core_emaill_email_t_166706_idx'), models.Index(fields=['success', '-created_at'], name='core_emaill_success_8402b6_idx')],
            },
        ),
    ]
