# Generated by Django 5.1.15 on 2026-03-26

import uuid

import django.db.models.deletion
from django.db import migrations, models


def generate_receipt_number() -> str:
    return f"MN-{uuid.uuid4().hex[:12].upper()}"


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="coupon",
            old_name="amount",
            new_name="discount_value",
        ),
        migrations.RenameField(
            model_name="coupon",
            old_name="min_order_amount",
            new_name="min_order_value",
        ),
        migrations.RenameField(
            model_name="coupon",
            old_name="usage_limit",
            new_name="max_uses",
        ),
        migrations.RenameField(
            model_name="coupon",
            old_name="times_used",
            new_name="used_count",
        ),
        migrations.RenameField(
            model_name="coupon",
            old_name="active",
            new_name="is_active",
        ),
        migrations.AddField(
            model_name="coupon",
            name="valid_from",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="coupon",
            name="valid_to",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cart",
            name="coupon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="carts",
                to="orders.coupon",
            ),
        ),
        migrations.AddField(
            model_name="cart",
            name="coupon_applied_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cart",
            name="delivery_region",
            field=models.CharField(
                choices=[
                    ("mombasa", "Mombasa (Same Day)"),
                    ("nairobi", "Nairobi (1-2 Days)"),
                    ("upcountry", "Upcountry (2-3 Days)"),
                ],
                default="nairobi",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="receipt_number",
            field=models.CharField(
                db_index=True, default=generate_receipt_number, editable=False, max_length=128, unique=True
            ),
        ),
    ]

