# Generated by Django 4.2.12 on 2026-02-23 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_cart_session_key_order_guest_email_order_guest_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_region',
            field=models.CharField(choices=[('mombasa', 'Mombasa (Same Day)'), ('nairobi', 'Nairobi (1-2 Days)'), ('upcountry', 'Upcountry (2-3 Days)')], default='nairobi', max_length=20),
        ),
    ]
