# Generated by Django 5.1.15 on 2026-03-28 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_backfill_missing_timestamps"),
        ("products", "0003_productvariant_image_alter_banner_id_alter_brand_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="variant_details",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="variant_reference",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=64,
                null=True,
            ),
        ),
    ]
