# Generated by Django 5.1.15 on 2026-04-18 12:29

import apps.orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderitem_variant_alter_cart_id_alter_cartitem_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='receipt_number',
            field=models.CharField(db_index=True, default=apps.orders.models.generate_receipt_number, editable=False, max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('initiated', 'Initiated'), ('paid', 'Paid'), ('payment_failed', 'Payment Failed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], db_index=True, default='pending', max_length=20),
        ),
    ]
