# Generated by ChatGPT on 2026-03-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_invoice_order_billing_address_order_billing_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="unit_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="cartitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(variant__isnull=True),
                fields=("cart", "product"),
                name="uniq_cart_product_no_variant",
            ),
        ),
        migrations.AddConstraint(
            model_name="cartitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(variant__isnull=False),
                fields=("cart", "variant"),
                name="uniq_cart_variant",
            ),
        ),
    ]
