# Generated by Django 5.1.15 on 2026-08-28 15:24

import apps.orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_mombasa_pickup_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, storage=apps.orders.models.invoice_pdf_storage, upload_to='invoices/%Y/%m/'),
        ),
    ]
