# Generated by Django 5.1.15 on 2026-09-14 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_cart_session_key_alter_invoice_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('mpesa', 'M-Pesa'), ('till', 'Lipa na M-Pesa - Till'), ('paypal', 'PayPal'), ('pesapal', 'Pesapal'), ('card', 'Credit/Debit Card'), ('bank', 'Bank Transfer'), ('cash', 'Cash on Delivery')], max_length=20, null=True),
        ),
    ]
