# Generated by Django 5.1.15 on 2026-03-22 23:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductEmbedding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('embedding', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AIGenerationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generation_type', models.CharField(choices=[('description', 'Product Description'), ('seo', 'SEO Metadata'), ('bundle', 'Bundle Generation'), ('chat', 'Chat Response')], max_length=20)),
                ('input_data', models.JSONField()),
                ('output_data', models.JSONField()),
                ('tokens_used', models.IntegerField(default=0)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['generation_type'], name='ai_aigenera_generat_386d44_idx'), models.Index(fields=['-created_at'], name='ai_aigenera_created_47c49a_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_id', models.CharField(db_index=True, max_length=100)),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('message', models.TextField()),
                ('response', models.TextField()),
                ('intent', models.CharField(blank=True, max_length=50)),
                ('products_shown', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session_id'], name='ai_chathist_session_261bed_idx'), models.Index(fields=['-created_at'], name='ai_chathist_created_1f0740_idx')],
            },
        ),
    ]
