/opt/kenya_baby_ecommerce/backend/logs/kenya_ecom.log {
    daily
    rotate 14
    compress
    missingok
    notifempty
    copytruncate
}
/var/log/celery/*.log {
    daily
    rotate 7
    compress
    missingok
    notifempty
    copytruncate
}
/var/log/gunicorn/*.log {
    daily
    rotate 14
    compress
    missingok
    notifempty
    copytruncate
}
