server {
    listen 80;
    server_name your.server.domain;

    client_max_body_size 20M;

    location /static/ {
        alias /opt/kenya_baby_ecommerce/backend/staticfiles/;
    }

    location /media/ {
        alias /opt/kenya_baby_ecommerce/backend/media/;
    }

    location / {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
        proxy_pass http://unix:/run/gunicorn.sock;
    }

    location /api/ {
        proxy_pass http://unix:/run/gunicorn.sock;
    }

    # Let's Encrypt Well-known
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }
}
