# Generated by Django 5.1.15 on 2026-08-28 15:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_password_reset_token_and_token_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(help_text='Kenyan format: +2547XXXXXXXX', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be in Kenyan format (+2547XXXXXXXX or +2541XXXXXXXX).', regex='^\\+254[71]\\d{8}$')]),
        ),
    ]
