# Generated by Django 5.1.15 on 2026-08-28 15:24
#
# Hardened for production: the unique=True constraint is applied DEFENSIVELY.
# The deploy runs `create_superuser || true` on every rollout, which can create
# duplicate phone_number values over time; a plain `ALTER TABLE ADD CONSTRAINT
# UNIQUE` would then raise and crash the backend boot with NO rollback (the
# compose health gate fails after ~5min and leaves the broken container up).
# This migration widens the column (always safe) and adds the UNIQUE constraint
# ONLY when (a) it doesn't already exist and (b) there are no duplicate non-null
# phone_number rows. App-level enforcement (full_clean in User.save) already
# prevents duplicates during normal operation.

from django.db import migrations, models
import django.core.validators


ADD_PHONE_UNIQUE_SQL = """
DO $malaika_add_phone_unique$
DECLARE
    dup int;
BEGIN
    -- Widen to match max_length=20 (idempotent; widening never loses data).
    ALTER TABLE accounts_user
        ALTER COLUMN phone_number TYPE varchar(20);

    -- Count duplicate non-null phone_number values.
    SELECT count(*) INTO dup FROM (
        SELECT phone_number, count(*)
        FROM accounts_user
        WHERE phone_number IS NOT NULL
          AND phone_number <> ''
        GROUP BY phone_number
        HAVING count(*) > 1
    ) d;

    -- Only attempt to add the constraint if it is not already present.
    IF (SELECT count(*) FROM pg_constraint
        WHERE conname = 'accounts_user_phone_number_key') = 0 THEN
        IF dup = 0 THEN
            ALTER TABLE accounts_user
                ADD CONSTRAINT accounts_user_phone_number_key UNIQUE (phone_number);
        ELSE
            RAISE NOTICE
                '[accounts.0003] Skipping UNIQUE constraint on accounts_user.phone_number: % duplicate value(s) present. App-level enforcement applies.',
                dup;
        END IF;
    END IF;
END
$malaika_add_phone_unique$;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_password_reset_token_and_token_version'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            # State declares the canonical field (matches the model: max_length=20,
            # unique=True, the Kenyan validator, help_text). This keeps
            # `makemigrations --check` green.
            state_operations=[
                migrations.AlterField(
                    model_name='user',
                    name='phone_number',
                    field=models.CharField(
                        help_text='Kenyan format: +2547XXXXXXXX',
                        max_length=20,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message='Phone number must be in Kenyan format (+2547XXXXXXXX or +2541XXXXXXXX).',
                                regex=r'^\+254[71]\d{8}$',
                            )
                        ],
                    ),
                ),
            ],
            # DB: do the safe widening + conditional unique constraint above.
            database_operations=[
                migrations.RunSQL(ADD_PHONE_UNIQUE_SQL, reverse_sql=migrations.RunSQL.noop),
            ],
        ),
    ]
