# Generated by ChatGPT on 2026-03-21

from django.db import migrations, models
from django.core.validators import RegexValidator


def forwards_role(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    User.objects.filter(role="admin").update(role="ADMIN")
    User.objects.filter(role="customer").update(role="CUSTOMER")


def backwards_role(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    User.objects.filter(role="ADMIN").update(role="admin")
    User.objects.filter(role="CUSTOMER").update(role="customer")


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_useraddress"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="phone",
            new_name="phone_number",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="email_verified",
            new_name="is_email_verified",
        ),
        migrations.AddField(
            model_name="user",
            name="full_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.RunPython(forwards_role, backwards_role),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("ADMIN", "Admin"), ("CUSTOMER", "Customer")],
                default="CUSTOMER",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                help_text="Kenyan format: +2547XXXXXXXX",
                max_length=20,
                unique=True,
                validators=[
                    RegexValidator(
                        message="Phone number must be in Kenyan format: +2547XXXXXXXX.",
                        regex="^\\+2547\\d{8}$",
                    )
                ],
            ),
        ),
    ]

