# Generated by Django 5.1.15 on 2026-03-08 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_invoice_order_billing_address_order_billing_city_and_more'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='payment',
            new_name='payments_pa_status_7ad4af_idx',
            old_name='payments_pa_status_94f286_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='payments_pa_payment_5c92d7_idx',
            old_name='payments_pa_payment_6fbc69_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='payments_pa_created_3147e3_idx',
            old_name='payments_pa_created_2fb92a_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentauditlog',
            new_name='payments_pa_event_t_18dee1_idx',
            old_name='payments_pa_event_t_a89056_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentauditlog',
            new_name='payments_pa_checkou_d6a607_idx',
            old_name='payments_pa_checkou_4148f9_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentauditlog',
            new_name='payments_pa_merchan_d8daf0_idx',
            old_name='payments_pa_merchan_0f9139_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentauditlog',
            new_name='payments_pa_result__b503e1_idx',
            old_name='payments_pa_result__5d9928_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentauditlog',
            new_name='payments_pa_payload_7ed8fa_idx',
            old_name='payments_pa_payload_393fc4_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentauditlog',
            new_name='payments_pa_created_255428_idx',
            old_name='payments_pa_created_d9d24a_idx',
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='orders.order'),
        ),
    ]
