# Generated by ChatGPT on 2026-03-21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_rename_payments_pa_status_94f286_idx_payments_pa_status_7ad4af_idx_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="phone",
            new_name="phone_number",
        ),
        migrations.RenameField(
            model_name="payment",
            old_name="checkout_request_id",
            new_name="mpesa_checkout_request_id",
        ),
        migrations.RenameField(
            model_name="payment",
            old_name="raw_callback",
            new_name="raw_callback_json",
        ),
        migrations.AddField(
            model_name="payment",
            name="callback_received_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="initiated_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]

