# Generated by Django 5.1.15 on 2026-07-20 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_backfill_legacy_payment_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='pesapal_confirmation_code',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='pesapal_merchant_reference',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='pesapal_tracking_id',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('paypal', 'PayPal'), ('card', 'Debit/Credit Card'), ('pesapal', 'Pesapal')], default='mpesa', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentauditlog',
            name='event_type',
            field=models.CharField(choices=[('callback_received', 'Callback Received'), ('callback_blocked', 'Callback Blocked'), ('callback_unmatched', 'Callback Unmatched'), ('callback_duplicate', 'Callback Duplicate'), ('callback_duplicate_receipt', 'Callback Duplicate Receipt'), ('callback_failed', 'Callback Failed'), ('callback_completed', 'Callback Completed'), ('stk_initiated', 'STK Initiated'), ('stk_failed', 'STK Failed'), ('reconcile_query', 'Reconcile Query'), ('reconcile_queued', 'Reconcile Queued'), ('reconcile_completed', 'Reconcile Completed'), ('pesapal_submitted', 'Pesapal Submitted'), ('ipn_received', 'IPN Received'), ('ipn_completed', 'IPN Completed'), ('ipn_failed', 'IPN Failed'), ('pesapal_cancelled', 'Pesapal Cancelled')], max_length=40),
        ),
    ]
