# Generated by Django 5.1.15 on 2026-03-22 23:27

import apps.products.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('button_text', models.CharField(blank=True, max_length=50)),
                ('button_link', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='banners/', validators=[apps.products.models.validate_image_file])),
                ('image_url', models.URLField(blank=True, help_text='Paste Cloudinary URL here instead of uploading', null=True)),
                ('mobile_image', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('mobile_image_url', models.URLField(blank=True, help_text='Paste Cloudinary URL for mobile', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('position', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['position', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', validators=[apps.products.models.validate_image_file])),
                ('group', models.CharField(blank=True, help_text='Top-level group for mega menu navigation', max_length=120)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='products.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('sku', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('compare_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('low_stock_threshold', models.PositiveIntegerField(default=5)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kg', max_digits=6, null=True)),
                ('gender', models.CharField(choices=[('boy', 'Boy'), ('girl', 'Girl'), ('unisex', 'Unisex')], default='unisex', max_length=10)),
                ('age_group', models.CharField(blank=True, choices=[('baby', 'Baby (0-2 years)'), ('toddler', 'Toddler (2-5 years)'), ('kids', 'Kids (6-12 years)')], max_length=20)),
                ('age_range', models.CharField(blank=True, choices=[('0-3 months', '0-3 months'), ('3-6 months', '3-6 months'), ('6-12 months', '6-12 months'), ('1-2 years', '1-2 years'), ('2-3 years', '2-3 years'), ('3-5 years', '3-5 years'), ('6-8 years', '6-8 years'), ('9-12 years', '9-12 years')], help_text='Recommended age range for browsing filters', max_length=50)),
                ('size_label', models.CharField(blank=True, choices=[('newborn', 'Newborn'), ('0-3m', '0-3M'), ('3-6m', '3-6M'), ('6-12m', '6-12M'), ('1y', '1Y'), ('2y', '2Y'), ('3y', '3Y'), ('4y', '4Y'), ('5y', '5Y'), ('6y', '6Y'), ('7y', '7Y'), ('8y', '8Y'), ('9y', '9Y'), ('10y', '10Y'), ('11y', '11Y'), ('12y', '12Y'), ('one-size', 'One Size')], max_length=20)),
                ('featured', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('seo_title', models.CharField(blank=True, max_length=70)),
                ('seo_description', models.CharField(blank=True, max_length=160)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', validators=[apps.products.models.validate_image_file])),
                ('is_active', models.BooleanField(default=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category')),
                ('tags', models.ManyToManyField(blank=True, related_name='products', to='products.tag')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('change_type', models.CharField(choices=[('order_placed', 'Order Placed'), ('order_cancelled', 'Order Cancelled'), ('restock', 'Restock'), ('manual_adjustment', 'Manual Adjustment')], max_length=30)),
                ('quantity_change', models.IntegerField()),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_logs', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_logs', to='products.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('reserved', models.PositiveIntegerField(default=0)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='products.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='products/gallery/', validators=[apps.products.models.validate_image_file])),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
            options={
                'ordering': ['position', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('size', models.CharField(blank=True, choices=[('newborn', 'Newborn'), ('0-3m', '0-3M'), ('3-6m', '3-6M'), ('6-12m', '6-12M'), ('1y', '1Y'), ('2y', '2Y'), ('3y', '3Y'), ('4y', '4Y'), ('5y', '5Y'), ('6y', '6Y'), ('7y', '7Y'), ('8y', '8Y'), ('9y', '9Y'), ('10y', '10Y'), ('11y', '11Y'), ('12y', '12Y'), ('one-size', 'One Size')], max_length=20, null=True)),
                ('color', models.CharField(blank=True, choices=[('white', 'White'), ('black', 'Black'), ('gray', 'Gray'), ('pink', 'Pink'), ('blue', 'Blue'), ('green', 'Green'), ('yellow', 'Yellow'), ('red', 'Red'), ('purple', 'Purple'), ('orange', 'Orange'), ('brown', 'Brown'), ('beige', 'Beige'), ('multi', 'Multi')], max_length=20, null=True)),
                ('sku', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('price_modifier', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_email', models.EmailField(blank=True, max_length=254)),
                ('rating', models.PositiveSmallIntegerField()),
                ('title', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField(blank=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VariantInventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('reserved', models.PositiveIntegerField(default=0)),
                ('variant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='products.productvariant')),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug'], name='products_ca_slug_da4386_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['group'], name='products_ca_group_0af2b5_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent'], name='products_ca_parent__f3c24e_idx'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('parent', 'slug'), name='uniq_category_parent_slug'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', True)), fields=('slug',), name='uniq_root_category_slug'),
        ),
        migrations.AddIndex(
            model_name='inventorylog',
            index=models.Index(fields=['product', '-created_at'], name='products_in_product_afd7cc_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorylog',
            index=models.Index(fields=['change_type'], name='products_in_change__8557b2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productimage',
            unique_together={('product', 'position')},
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['product', 'size', 'color'], name='products_pr_product_fb9cfd_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['sku'], name='products_pr_sku_dcab68_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('product', 'size', 'color')},
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['product'], name='products_re_product_b03620_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['-created_at'], name='products_re_created_351f12_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('product', 'user')},
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='products_pr_slug_3edc0c_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku'], name='products_pr_sku_ca0cdc_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='products_pr_name_9ff0a3_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-created_at'], name='products_pr_created_bce1a7_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', '-created_at'], name='products_pr_is_acti_645007_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'is_active'], name='products_pr_categor_50f5f1_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price'], name='products_pr_price_9b1a5f_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['featured'], name='products_pr_feature_55f52f_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status'], name='products_pr_status_041708_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['age_group'], name='products_pr_age_gro_d6c86f_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['age_range'], name='products_pr_age_ran_2ac13e_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['gender'], name='products_pr_gender_b0135f_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['size_label'], name='products_pr_size_la_ae005c_idx'),
        ),
        migrations.AddIndex(
            model_name='variantinventory',
            index=models.Index(fields=['quantity'], name='products_va_quantit_2374b8_idx'),
        ),
        migrations.AddIndex(
            model_name='variantinventory',
            index=models.Index(fields=['variant'], name='products_va_variant_e07f49_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('user', 'product')},
        ),
    ]
