# Generated by Django 5.1.15 on 2026-03-28 11:40

import apps.products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_backfill_missing_timestamps"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="products/variants/",
                validators=[apps.products.models.validate_image_file],
            ),
        ),
    ]
