# Generated by Django 5.1.15 on 2026-07-17 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productvariant_image_alter_banner_id_alter_brand_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='button_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
