# Generated by Django 4.2.12 on 2026-02-23 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, choices=[('0-3m', '0-3 Months'), ('3-6m', '3-6 Months'), ('6-9m', '6-9 Months'), ('9-12m', '9-12 Months'), ('12-18m', '12-18 Months'), ('18-24m', '18-24 Months'), ('2-3y', '2-3 Years'), ('3-4y', '3-4 Years'), ('4-5y', '4-5 Years'), ('one-size', 'One Size')], max_length=20, null=True)),
                ('color', models.CharField(blank=True, choices=[('white', 'White'), ('black', 'Black'), ('gray', 'Gray'), ('pink', 'Pink'), ('blue', 'Blue'), ('green', 'Green'), ('yellow', 'Yellow'), ('red', 'Red'), ('purple', 'Purple'), ('orange', 'Orange'), ('brown', 'Brown'), ('beige', 'Beige'), ('multi', 'Multi')], max_length=20, null=True)),
                ('sku', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('price_modifier', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', '-created_at'], name='products_pr_is_acti_645007_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'is_active'], name='products_pr_categor_50f5f1_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price'], name='products_pr_price_9b1a5f_idx'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['product', 'size', 'color'], name='products_pr_product_fb9cfd_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['sku'], name='products_pr_sku_dcab68_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('product', 'size', 'color')},
        ),
    ]
