# Generated by Django 5.1.15 on 2026-09-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='product',
            name='fabric',
            field=models.TextField(blank=True, help_text='Fabric / material and care instructions shown on the product page'),
        ),
        migrations.AddField(
            model_name='product',
            name='whats_included',
            field=models.TextField(blank=True, help_text="What's included in the package (e.g. 'Pack of 3 onesies')"),
        ),
    ]
