# Generated by Django 5.1.15 on 2026-09-14 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_brand_options_product_fabric_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('new', 'Brand New'), ('mtumba', 'Mtumba (Pre-Loved)')], db_index=True, default='new', help_text='Mtumba items are quality-checked second-hand clothes, sold as-is.', max_length=12),
        ),
    ]
