# Generated by Django 5.1.15 on 2026-03-08 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_banner_image_alter_category_image_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='variantinventory',
            index=models.Index(fields=['quantity'], name='products_va_quantit_2374b8_idx'),
        ),
        migrations.AddIndex(
            model_name='variantinventory',
            index=models.Index(fields=['variant'], name='products_va_variant_e07f49_idx'),
        ),
    ]
