# Generated by Django 5.1.15 on 2026-03-09 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_invoice_order_billing_address_order_billing_city_and_more'),
        ('products', '0011_variantinventory_products_va_quantit_2374b8_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('order_placed', 'Order Placed'), ('order_cancelled', 'Order Cancelled'), ('restock', 'Restock'), ('manual_adjustment', 'Manual Adjustment')], max_length=30)),
                ('quantity_change', models.IntegerField()),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='age_group',
            field=models.CharField(blank=True, choices=[('baby', 'Baby (0-2 years)'), ('toddler', 'Toddler (2-5 years)'), ('kids', 'Kids (6-12 years)')], max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='compare_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='size_label',
            field=models.CharField(blank=True, choices=[('newborn', 'Newborn'), ('0-3m', '0-3M'), ('3-6m', '3-6M'), ('6-12m', '6-12M'), ('1y', '1Y'), ('2y', '2Y'), ('3y', '3Y'), ('4y', '4Y'), ('5y', '5Y'), ('6y', '6Y'), ('7y', '7Y'), ('8y', '8Y'), ('9y', '9Y'), ('10y', '10Y'), ('11y', '11Y'), ('12y', '12Y'), ('one-size', 'One Size')], max_length=20),
        ),
        migrations.AddField(
            model_name='productimage',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=140),
        ),
        migrations.AlterField(
            model_name='product',
            name='age_range',
            field=models.CharField(blank=True, choices=[('0-3 months', '0-3 months'), ('3-6 months', '3-6 months'), ('6-12 months', '6-12 months'), ('1-2 years', '1-2 years'), ('2-3 years', '2-3 years'), ('3-5 years', '3-5 years'), ('6-8 years', '6-8 years'), ('9-12 years', '9-12 years')], help_text='Recommended age range for browsing filters', max_length=50),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='size',
            field=models.CharField(blank=True, choices=[('newborn', 'Newborn'), ('0-3m', '0-3M'), ('3-6m', '3-6M'), ('6-12m', '6-12M'), ('1y', '1Y'), ('2y', '2Y'), ('3y', '3Y'), ('4y', '4Y'), ('5y', '5Y'), ('6y', '6Y'), ('7y', '7Y'), ('8y', '8Y'), ('9y', '9Y'), ('10y', '10Y'), ('11y', '11Y'), ('12y', '12Y'), ('one-size', 'One Size')], max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug'], name='products_ca_slug_da4386_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['group'], name='products_ca_group_0af2b5_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent'], name='products_ca_parent__f3c24e_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['age_group'], name='products_pr_age_gro_d6c86f_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['age_range'], name='products_pr_age_ran_2ac13e_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['gender'], name='products_pr_gender_b0135f_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['size_label'], name='products_pr_size_la_ae005c_idx'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('parent', 'slug'), name='uniq_category_parent_slug'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', True)), fields=('slug',), name='uniq_root_category_slug'),
        ),
        migrations.AddField(
            model_name='inventorylog',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_logs', to='orders.order'),
        ),
        migrations.AddField(
            model_name='inventorylog',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_logs', to='products.product'),
        ),
        migrations.AddIndex(
            model_name='inventorylog',
            index=models.Index(fields=['product', '-created_at'], name='products_in_product_afd7cc_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorylog',
            index=models.Index(fields=['change_type'], name='products_in_change__8557b2_idx'),
        ),
    ]
