# Generated by Django 5.1.15 on 2026-03-13 08:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0011_banner_cloudinary_urls"),
        ("products", "0012_inventorylog_alter_category_options_and_more"),
    ]

    operations = []

